### PR TITLE
Add EditTreeEncoder for encoding/decoding lemmatization

### PR DESCRIPTION
**Pull request by danieldk**

### CODE REVIEW

**Review by twuebi — APPROVED** [review]

**Review by twuebi — APPROVED** [review]
The wrapper is necessary since you want proper strings instead of debug strings of `Vec<char>`?

edit: haha, seems I forgot that I already reviewed this yesterday, sometimes hitting refresh may help :)

**Comment by danieldk** [comment]
> The wrapper is necessary since you want proper strings instead of debug strings of `Vec<char>`?

Yes, `ToString` is used in the tagger wrapper (without type parameters) to get top-k results. `Debug` representations are really ugly for downstream users.

**Comment by danieldk** [comment]
I might reimplement `Serialize`/`Deserialize` though, so that the serialized variant will not have the wrapping.

**Comment by danieldk** [comment]
> > The wrapper is necessary since you want proper strings instead of debug strings of `Vec<char>`?
> 
> Yes, `ToString` is used in the tagger wrapper (without type parameters) to get top-k results. `Debug` representations are really ugly for downstream users.

I should follow-up: would you accept the `Display` implementation of this crate in `edit_tree`? Because then we could remove the wrapping here.

**Comment by twuebi** [comment]
https://github.com/twuebi/edit_tree/pull/11

**Comment by twuebi** [comment]
The new `Display` implementation is now on crates.io, it's published as `0.1.1`, realized later that this probably should have been `0.2`

**Pull request merged**
